// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvayx4QLvWNQtIZQ7lYAco0wRSoVzt0U',
    appId: '1:650960573029:web:ebb5556de2a5e421532c8c',
    messagingSenderId: '650960573029',
    projectId: 'aqui-ajuda-8b69b',
    authDomain: 'aqui-ajuda-8b69b.firebaseapp.com',
    storageBucket: 'aqui-ajuda-8b69b.firebasestorage.app',
    measurementId: 'G-Z7X946RZVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi2EbNsMD0NOepFAhtiRBV4lCtEDRreaE',
    appId: '1:650960573029:android:27cebb6805dac681532c8c',
    messagingSenderId: '650960573029',
    projectId: 'aqui-ajuda-8b69b',
    storageBucket: 'aqui-ajuda-8b69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVR9ppTAhVJHYWhqumUNg8FoA66xsFBbc',
    appId: '1:650960573029:ios:54b22e1ebb4b9e50532c8c',
    messagingSenderId: '650960573029',
    projectId: 'aqui-ajuda-8b69b',
    storageBucket: 'aqui-ajuda-8b69b.firebasestorage.app',
    androidClientId:
        '650960573029-rjj906hdiva4486oanluo373hglf5h6b.apps.googleusercontent.com',
    iosClientId:
        '650960573029-qpvnmhoqs67uv0cgp78dkfibg1ghbtpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquiAjudaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVR9ppTAhVJHYWhqumUNg8FoA66xsFBbc',
    appId: '1:650960573029:ios:54b22e1ebb4b9e50532c8c',
    messagingSenderId: '650960573029',
    projectId: 'aqui-ajuda-8b69b',
    storageBucket: 'aqui-ajuda-8b69b.firebasestorage.app',
    androidClientId:
        '650960573029-rjj906hdiva4486oanluo373hglf5h6b.apps.googleusercontent.com',
    iosClientId:
        '650960573029-qpvnmhoqs67uv0cgp78dkfibg1ghbtpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquiAjudaApp',
  );
}
